#!/bin/sh
#
# name     : tmuxen, tmux environment made easy
# author   : Li Wengang  <wgl.liwengang@gmail.com>; Li Chao <lichao8633@gmail.com>
# license  : GPL
# created  : 2012 Aug 13
#

cmd=$(which tmux)      # tmux path
session=$(hostname -s) # session name

if [ -z $cmd ]; then
    echo "You need to install tmux."
    exit 1
fi

$cmd has -t $session 2> /dev/null

if [ $? != 0 ]; then
    $cmd new -d -n bash -s $session "bash"
    $cmd neww -n bash1 -t $session "bash"
    $cmd neww -n bash2 -t $session "bash"
    $cmd neww -n bash3 -t $session "bash"
    $cmd neww -n bash4 -t $session "bash"
#    $cmd neww -n zsh0 -t $session "zsh"
#    $cmd neww -n zsh1 -t $session "zsh"
    #$cmd splitw -h -p 50 -t $session "mutt"
    $cmd selectw -t $session:1
fi

$cmd att -t $session

exit 0
